language: php
php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - mysql -e 'create database lindale;'
  - composer self-update
  - composer install
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate

script:
  - phpunit

notifications:
  emails:
    - kudouyoichi@gmail.com